### ISSUE TITLE
Upgrade librdkafka build pack to v1.2.2

### ISSUE THREAD

**Issue by ge-stalt** [HDVInsurance/heroku-buildpack-librdkafka#1]
This module is needed by node-rdkafka.

This is causing an error currently because the librdkafka features are undefined.

 2019-12-03T18:04:34.035Z sinek:nproducer:error TypeError: Cannot read property 'split' of undefined
2019-12-03T18:04:34.035735+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/node-rdkafka/lib/index.js:18:30)
2019-12-03T18:04:34.035737+00:00 app[web.1]:     at Module._compile (internal/modules/cjs/loader.js:956:30)
2019-12-03T18:04:34.035738+00:00 app[web.1]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
2019-12-03T18:04:34.035740+00:00 app[web.1]:     at Module.load (internal/modules/cjs/loader.js:812:32)
2019-12-03T18:04:34.035741+00:00 app[web.1]:     at Function.Module._load (internal/modules/cjs/loader.js:724:14)
2019-12-03T18:04:34.035743+00:00 app[web.1]:     at Module.require (internal/modules/cjs/loader.js:849:19)

**Comment by ge-stalt** [comment]
completed and merged
